-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 22:53:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
    -- Schema db_mascotas
-- -----------------------------------------------------

    -- -----------------------------------------------------
        -- Schema db_mascotas
-- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `db_mascotas` DEFAULT CHARACTER SET utf8 ;
USE `db_mascotas` ;

-- -----------------------------------------------------
    -- Table `db_mascotas`.`tipo_mascota`
-- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `db_mascotas`.`tipo_mascota` (
    `idtipo_mascota` INT NOT NULL,
    `descripcion` VARCHAR(45) NULL,
    PRIMARY KEY (`idtipo_mascota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
    -- Table `db_mascotas`.`propietario`
-- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `db_mascotas`.`propietario` (
    `idpropietario` INT NOT NULL,
    `nombre` VARCHAR(45) NULL,
    `direccion` VARCHAR(45) NULL,
    `telefono` VARCHAR(45) NULL,
    `correo` VARCHAR(45) NULL,
    `comentario` LONGTEXT NULL,
    PRIMARY KEY (`idpropietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
    -- Table `db_mascotas`.`mascota`
-- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `db_mascotas`.`mascota` (
    `idmascota` INT NOT NULL,
    `nombre` VARCHAR(45) NULL,
    `propietario` INT NULL,
    `tipo_mascota_idtipo_mascota` INT NOT NULL,
    `propietario_idpropietario` INT NOT NULL,
    PRIMARY KEY (`idmascota`),
    INDEX `fk_mascota_tipo_mascota1_idx` (`tipo_mascota_idtipo_mascota` ASC),
    INDEX `fk_mascota_propietario1_idx` (`propietario_idpropietario` ASC),
    CONSTRAINT `fk_mascota_tipo_mascota1`
FOREIGN KEY (`tipo_mascota_idtipo_mascota`)
REFERENCES `db_mascotas`.`tipo_mascota` (`idtipo_mascota`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
    CONSTRAINT `fk_mascota_propietario1`
FOREIGN KEY (`propietario_idpropietario`)
REFERENCES `db_mascotas`.`propietario` (`idpropietario`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
