# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EowqzYUnSeMquDtV2elAxcOjKQzyP4iO

1- ¿Cuál es el resultado de ejecutar el siguiente pseudo-código con el valor “5”?
"""

def metodoQueHaceAlgo(valor):
  if (valor < 3):
    return valor
  return metodoQueHaceAlgo(valor-1)*metodoQueHaceAlgo(valor-2)

metodoQueHaceAlgo(5)

"""El resultado que se muestra al lanzar la función metodoQueHaceAlgo con el valor de 5 es de "**8**"

2- Realice un algoritmo que reciba como parámetro dos números enteros y retorne la división de ambos números.
"""

def divicionDosnum(valor1, valor2):
  return valor1/valor2

divicionDosnum(3,4)

divicionDosnum(6,2)

"""3- Un entero positivo se llama perfecto si éste es igual a la suma de todos sus divisores diferentes de él. Por ejemplo:

6 es perfecto porque 6 = 1 + 2 + 3.

28 es perfecto porque 28 = 1 + 2 + 4 + 7 + 14

Escriba un programa que reciba como entrada n números enteros positivos, y por cada uno de ellos imprima sus divisores e indique si es perfecto o no.
"""

import numpy as np

print(valores)
def numeroPerfecto(valores):
  num = []
  t = 0
  numt = ""
  for valor in valores: 
    for i in range(1, valor):
      if (valor%i == 0):
        num.append(i)
        t = t + i
    for n in num:
      if ( numt == ""):
        numt = str(valor) + " es perfecto porque " + str(valor) + " = " + str(n)
      else:
        numt =numt +" + " + str(n)
  
    if (t == valor):
      numt = numt + " = " + str(t) + "\n"
      print(numt)
      num = []
      t = 0
      numt = ""
    else:
      num = []
      t = 0
      numt = ""

numeros = range(1,1000)
numeroPerfecto(numeros)

"""4. """

for a in range(1,100):
    if (a%5 == 0 and a%3 == 0):
       print('fizzbuzz', end='\n')
    elif a%5 == 0:
       print('buzz', end='\n')
    elif a%3 == 0:
       print('fizz', end='\n')
    else:
       print(a, end='\n')